Update Dockerfile-render

diff --git a/Dockerfile-render b/Dockerfile-render
--- a/Dockerfile-render
+++ b/Dockerfile-render
@@ -137,9 +137,9 @@ RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &
 	# setcap cap_net_bind_service=+ep /usr/bin/clockdiff
 
 RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/ping || setcap cap_net_admin,cap_net_raw+ep /bin/ping || echo "==ERROR: setcap ping=="
-RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/ping6 || setcap cap_net_admin,cap_net_raw+ep /bin/ping6 || echo "==ERROR: setcap ping6=="
-RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/tracepath || echo "==ERROR: setcap tracepath=="
-RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/clockdiff || echo "==ERROR: setcap clockdiff=="
+#RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/ping6 || setcap cap_net_admin,cap_net_raw+ep /bin/ping6 || echo "==ERROR: setcap ping6=="
+#RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/tracepath || echo "==ERROR: setcap tracepath=="
+#RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/clockdiff || echo "==ERROR: setcap clockdiff=="
 RUN setcap cap_net_admin,cap_net_raw+ep /usr/local/bin/node || echo "==ERROR: setcap node=="
 
 # Expose the application port
@@ -154,4 +154,4 @@ HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
 USER $USERNAME
 
 ENTRYPOINT ["/app/entrypoint.sh"]
-CMD ["node", "main"]
+CMD ["/usr/local/bin/node", "main"]
